[package]
name = "rust_learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = false

[dependencies]
learn_macro = {path="./learn_macro"}
rand="0.8.5"
